In [1]:
import pandas as pd

# Merge Test Dataframes

In [2]:
# test_dates = pd.read_csv('test_dates.csv')
test_df = pd.read_csv('new_test.csv')
items = pd.read_csv('new_items.csv')                                    # MERGE ON  --item_nbr
test_store_transactions = pd.read_csv('test_store_transactions.csv')    # MERGE ON -- date, month, day, year
test_holidays = pd.read_csv('test_holidays.csv')                        # MERGE ON -- date, month, day, year
test_oil = pd.read_csv('test_oil.csv')                                  # MERGE ON -- date, month, day, year

In [3]:
test_df

,date,month,day,year,id,store_nbr,item_nbr,onpromotion
0,2017-08-16,8,16,2017,125497040,1,96995,0
1,2017-08-16,8,16,2017,125497041,1,99197,0
2,2017-08-16,8,16,2017,125497042,1,103501,0
3,2017-08-16,8,16,2017,125497043,1,103520,0
4,2017-08-16,8,16,2017,125497044,1,103665,0
5,2017-08-16,8,16,2017,125497045,1,105574,0
6,2017-08-16,8,16,2017,125497046,1,105575,0
7,2017-08-16,8,16,2017,125497047,1,105576,0
8,2017-08-16,8,16,2017,125497048,1,105577,0
9,2017-08-16,8,16,2017,125497049,1,105693,0
10,2017-08-16,8,16,2017,125497050,1,105737,0
11,2017-08-16,8,16,2017,125497051,1,105857,0
12,2017-08-16,8,16,2017,125497052,1,106716,0
13,2017-08-16,8,16,2017,125497053,1,108079,0
14,2017-08-16,8,16,2017,125497054,1,108634,0
15,2017-08-16,8,16,2017,125497055,1,108696,0
16,2017-08-16,8,16,2017,125497056,1,108698,0
17,2017-08-16,8,16,2017,125497057,1,108701,1
18,2017-08-16,8,16,2017,125497058,1,108786,0
19,2017-08-16,8,16,2017,125497059,1,108797,1
20,2017-08-16,8,16,2017,125497060,1,108831,0
21,2017-08-16,8,16,2017,125497061,1,108833,0
22,2017-08-16,8,16,2017,125497062,1,108862,0
23,2017-08-16,8,16,2017,125497063,1,108952,0
24,2017-08-16,8,16,2017,125497064,1,111223,0
25,2017-08-16,8,16,2017,125497065,1,111397,0
26,2017-08-16,8,16,2017,125497066,1,112830,0
27,2017-08-16,8,16,2017,125497067,1,114778,0
28,2017-08-16,8,16,2017,125497068,1,114790,1
29,2017-08-16,8,16,2017,125497069,1,114799,0
...,...,...,...,...,...,...,...,...
3370434,2017-08-31,8,31,2017,128867474,54,2127921,0
3370435,2017-08-31,8,31,2017,128867475,54,2127992,0
3370436,2017-08-31,8,31,2017,128867476,54,2128628,0
3370437,2017-08-31,8,31,2017,128867477,54,2128799,0
3370438,2017-08-31,8,31,2017,128867478,54,2129334,0
3370439,2017-08-31,8,31,2017,128867479,54,2129350,0
3370440,2017-08-31,8,31,2017,128867480,54,2129387,0
3370441,2017-08-31,8,31,2017,128867481,54,2129515,0
3370442,2017-08-31,8,31,2017,128867482,54,2129616,0
3370443,2017-08-31,8,31,2017,128867483,54,2129678,0
3370444,2017-08-31,8,31,2017,128867484,54,2129786,0
3370445,2017-08-31,8,31,2017,128867485,54,2129790,0
3370446,2017-08-31,8,31,2017,128867486,54,2129892,0
3370447,2017-08-31,8,31,2017,128867487,54,2129994,0
3370448,2017-08-31,8,31,2017,128867488,54,2130131,0
3370449,2017-08-31,8,31,2017,128867489,54,2130219,0
3370450,2017-08-31,8,31,2017,128867490,54,2130265,0
3370451,2017-08-31,8,31,2017,128867491,54,2130352,0
3370452,2017-08-31,8,31,2017,128867492,54,2130474,0
3370453,2017-08-31,8,31,2017,128867493,54,2130521,0
3370454,2017-08-31,8,31,2017,128867494,54,2130526,0
3370455,2017-08-31,8,31,2017,128867495,54,2130553,0
3370456,2017-08-31,8,31,2017,128867496,54,2131010,0
3370457,2017-08-31,8,31,2017,128867497,54,2131572,0
3370458,2017-08-31,8,31,2017,128867498,54,2131699,0
3370459,2017-08-31,8,31,2017,128867499,54,2132163,0
3370460,2017-08-31,8,31,2017,128867500,54,2132318,0
3370461,2017-08-31,8,31,2017,128867501,54,2132945,0
3370462,2017-08-31,8,31,2017,128867502,54,2132957,0
3370463,2017-08-31,8,31,2017,128867503,54,2134244,0

In [7]:
test_df = test_df.merge(items, on='item_nbr')
test_df.sort_values(by=['id'], inplace=True)
test_df.reset_index(drop=True, inplace=True)
test_df = test_df.merge(test_store_transactions, on=['date','month','day','year'])
test_df = test_df.merge(test_holidays, on=['date','month','day','year'])
test_df = test_df.merge(test_oil, on=['date','month','day','year'])
test_df

,date,month,day,year,id,store_nbr,item_nbr,onpromotion,perishable,AUTOMOTIVE,...,locale_name__Quito,locale_name__Riobamba,locale_name__Salinas,locale_name__Santa Elena,locale_name__Santo Domingo,locale_name__Santo Domingo de los Tsachilas,transferred,dcoilwtico,oil/100,oil_change
0,2017-08-16,8,16,2017,125497040,1,96995,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
1,2017-08-16,8,16,2017,125497041,1,99197,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
2,2017-08-16,8,16,2017,125497042,1,103501,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
3,2017-08-16,8,16,2017,125497043,1,103520,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
4,2017-08-16,8,16,2017,125497044,1,103665,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
5,2017-08-16,8,16,2017,125497045,1,105574,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
6,2017-08-16,8,16,2017,125497046,1,105575,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
7,2017-08-16,8,16,2017,125497047,1,105576,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
8,2017-08-16,8,16,2017,125497048,1,105577,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
9,2017-08-16,8,16,2017,125497049,1,105693,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
10,2017-08-16,8,16,2017,125497050,1,105737,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
11,2017-08-16,8,16,2017,125497051,1,105857,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
12,2017-08-16,8,16,2017,125497052,1,106716,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
13,2017-08-16,8,16,2017,125497053,1,108079,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
14,2017-08-16,8,16,2017,125497054,1,108634,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
15,2017-08-16,8,16,2017,125497055,1,108696,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
16,2017-08-16,8,16,2017,125497056,1,108698,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
17,2017-08-16,8,16,2017,125497057,1,108701,1,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
18,2017-08-16,8,16,2017,125497058,1,108786,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
19,2017-08-16,8,16,2017,125497059,1,108797,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
20,2017-08-16,8,16,2017,125497060,1,108831,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
21,2017-08-16,8,16,2017,125497061,1,108833,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
22,2017-08-16,8,16,2017,125497062,1,108862,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
23,2017-08-16,8,16,2017,125497063,1,108952,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
24,2017-08-16,8,16,2017,125497064,1,111223,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
25,2017-08-16,8,16,2017,125497065,1,111397,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
26,2017-08-16,8,16,2017,125497066,1,112830,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
27,2017-08-16,8,16,2017,125497067,1,114778,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
28,2017-08-16,8,16,2017,125497068,1,114790,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
29,2017-08-16,8,16,2017,125497069,1,114799,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3370434,2017-08-31,8,31,2017,128867474,54,2127921,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370435,2017-08-31,8,31,2017,128867475,54,2127992,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370436,2017-08-31,8,31,2017,128867476,54,2128628,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370437,2017-08-31,8,31,2017,128867477,54,2128799,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370438,2017-08-31,8,31,2017,128867478,54,2129334,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370439,2017-08-31,8,31,2017,128867479,54,2129350,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370440,2017-08-31,8,31,2017,128867480,54,2129387,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370441,2017-08-31,8,31,2017,128867481,54,2129515,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370442,2017-08-31,8,31,2017,128867482,54,2129616,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370443,2017-08-31,8,31,2017,128867483,54,2129678,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370444,2017-08-31,8,31,2017,128867484,54,2129786,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370445,2017-08-31,8,31,2017,128867485,54,2129790,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370446,2017-08-31,8,31,2017,128867486,54,2129892,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370447,2017-08-31,8,31,2017,128867487,54,2129994,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370448,2017-08-31,8,31,2017,128867488,54,2130131,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370449,2017-08-31,8,31,2017,128867489,54,2130219,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370450,2017-08-31,8,31,2017,128867490,54,2130265,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370451,2017-08-31,8,31,2017,128867491,54,2130352,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370452,2017-08-31,8,31,2017,128867492,54,2130474,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370453,2017-08-31,8,31,2017,128867493,54,2130521,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370454,2017-08-31,8,31,2017,128867494,54,2130526,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370455,2017-08-31,8,31,2017,128867495,54,2130553,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370456,2017-08-31,8,31,2017,128867496,54,2131010,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370457,2017-08-31,8,31,2017,128867497,54,2131572,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370458,2017-08-31,8,31,2017,128867498,54,2131699,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370459,2017-08-31,8,31,2017,128867499,54,2132163,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370460,2017-08-31,8,31,2017,128867500,54,2132318,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370461,2017-08-31,8,31,2017,128867501,54,2132945,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370462,2017-08-31,8,31,2017,128867502,54,2132957,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370463,2017-08-31,8,31,2017,128867503,54,2134244,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30

In [8]:
test_df.to_csv('TEST_FINAL.csv', index=False, chunksize=200000)

# Merge Without Items DF

In [1]:
import pandas as pd
# test_dates = pd.read_csv('test_dates.csv')
test_df = pd.read_csv('new_test.csv')
test_store_transactions = pd.read_csv('test_store_transactions.csv')    # MERGE ON -- date, month, day, year
test_holidays = pd.read_csv('test_holidays.csv')                        # MERGE ON -- date, month, day, year
test_oil = pd.read_csv('test_oil.csv')                                  # MERGE ON -- date, month, day, year

In [2]:
test_df = test_df.merge(test_store_transactions, on=['date','month','day','year'])
test_df = test_df.merge(test_holidays, on=['date','month','day','year'])
test_df = test_df.merge(test_oil, on=['date','month','day','year'])
test_df

,date,month,day,year,id,store_nbr,item_nbr,onpromotion,transactions,city__Ambato,...,locale_name__Quito,locale_name__Riobamba,locale_name__Salinas,locale_name__Santa Elena,locale_name__Santo Domingo,locale_name__Santo Domingo de los Tsachilas,transferred,dcoilwtico,oil/100,oil_change
0,2017-08-16,8,16,2017,125497040,1,96995,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
1,2017-08-16,8,16,2017,125497041,1,99197,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
2,2017-08-16,8,16,2017,125497042,1,103501,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
3,2017-08-16,8,16,2017,125497043,1,103520,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
4,2017-08-16,8,16,2017,125497044,1,103665,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
5,2017-08-16,8,16,2017,125497045,1,105574,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
6,2017-08-16,8,16,2017,125497046,1,105575,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
7,2017-08-16,8,16,2017,125497047,1,105576,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
8,2017-08-16,8,16,2017,125497048,1,105577,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
9,2017-08-16,8,16,2017,125497049,1,105693,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
10,2017-08-16,8,16,2017,125497050,1,105737,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
11,2017-08-16,8,16,2017,125497051,1,105857,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
12,2017-08-16,8,16,2017,125497052,1,106716,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
13,2017-08-16,8,16,2017,125497053,1,108079,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
14,2017-08-16,8,16,2017,125497054,1,108634,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
15,2017-08-16,8,16,2017,125497055,1,108696,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
16,2017-08-16,8,16,2017,125497056,1,108698,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
17,2017-08-16,8,16,2017,125497057,1,108701,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
18,2017-08-16,8,16,2017,125497058,1,108786,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
19,2017-08-16,8,16,2017,125497059,1,108797,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
20,2017-08-16,8,16,2017,125497060,1,108831,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
21,2017-08-16,8,16,2017,125497061,1,108833,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
22,2017-08-16,8,16,2017,125497062,1,108862,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
23,2017-08-16,8,16,2017,125497063,1,108952,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
24,2017-08-16,8,16,2017,125497064,1,111223,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
25,2017-08-16,8,16,2017,125497065,1,111397,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
26,2017-08-16,8,16,2017,125497066,1,112830,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
27,2017-08-16,8,16,2017,125497067,1,114778,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
28,2017-08-16,8,16,2017,125497068,1,114790,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
29,2017-08-16,8,16,2017,125497069,1,114799,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.80,0.4680,-0.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3370434,2017-08-31,8,31,2017,128867474,54,2127921,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370435,2017-08-31,8,31,2017,128867475,54,2127992,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370436,2017-08-31,8,31,2017,128867476,54,2128628,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370437,2017-08-31,8,31,2017,128867477,54,2128799,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370438,2017-08-31,8,31,2017,128867478,54,2129334,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370439,2017-08-31,8,31,2017,128867479,54,2129350,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370440,2017-08-31,8,31,2017,128867480,54,2129387,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370441,2017-08-31,8,31,2017,128867481,54,2129515,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370442,2017-08-31,8,31,2017,128867482,54,2129616,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370443,2017-08-31,8,31,2017,128867483,54,2129678,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370444,2017-08-31,8,31,2017,128867484,54,2129786,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370445,2017-08-31,8,31,2017,128867485,54,2129790,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370446,2017-08-31,8,31,2017,128867486,54,2129892,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370447,2017-08-31,8,31,2017,128867487,54,2129994,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370448,2017-08-31,8,31,2017,128867488,54,2130131,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370449,2017-08-31,8,31,2017,128867489,54,2130219,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370450,2017-08-31,8,31,2017,128867490,54,2130265,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370451,2017-08-31,8,31,2017,128867491,54,2130352,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370452,2017-08-31,8,31,2017,128867492,54,2130474,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370453,2017-08-31,8,31,2017,128867493,54,2130521,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370454,2017-08-31,8,31,2017,128867494,54,2130526,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370455,2017-08-31,8,31,2017,128867495,54,2130553,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370456,2017-08-31,8,31,2017,128867496,54,2131010,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370457,2017-08-31,8,31,2017,128867497,54,2131572,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370458,2017-08-31,8,31,2017,128867498,54,2131699,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370459,2017-08-31,8,31,2017,128867499,54,2132163,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370460,2017-08-31,8,31,2017,128867500,54,2132318,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370461,2017-08-31,8,31,2017,128867501,54,2132945,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370462,2017-08-31,8,31,2017,128867502,54,2132957,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30
3370463,2017-08-31,8,31,2017,128867503,54,2134244,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.26,0.4726,1.30

In [ ]:
test_df.drop('oil/100', axis=1, inplace=True)
test_df.drop('date', axis=1, inplace=True)
#test_df.fillna(0, inplace=True)

In [ ]:
columns = test_df.columns.values

for c in columns:
    new_c = c
    new_c.replace(' ', '_')
    test_df.rename(columns={c:new_c}, inplace=True)

In [3]:
test_df.to_csv('TEST_FINAL_NO_ITEMS.csv', index=False, chunksize=200000)